development:
  adapter: postgresql
  host: localhost
  database: films_ember_development
  pool: 5
  username: postgres
  password: superv1ll4
test:
  adapter: postgresql
  database: my_datbase_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_datbase_production
  pool: 5
  timeout: 5000